FROM node:16.17.0 as build
WORKDIR /app
COPY package*.json ./
RUN npm install npm@8.19.1
RUN npm install
COPY . .
CMD npm run build

FROM nginx
COPY --from=build /app/build /usr/share/nginx/html
#docker-compose -f docker-compose.yml -f docker-compose-prod.yml up -d --build