version: "3"
services:
  portfolio_frontend:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    environment:
      - REACT_APP_NAME=sovan
      - CHOKDIR_USEPOLLING=true